version: '3.3'

services:
  server:
    build: server
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      PORT: ${SERVER_PORT}
      HOST: ${SERVER_HOST}
      FRONTEND_URL: ${FRONTEND_URL}
    links:
      - todolistdb
    depends_on:
      - todolistdb

  socket-server:
    build: socket-server
    ports:
      - "9090:9090"
    restart: always
    environment:
      PORT: ${SOCKET_IO_PORT}
      HOST: ${SOCKET_IO_HOST}
      FRONTEND_URL: ${FRONTEND_URL}
    links:
      - todolistdb
    depends_on:
      - todolistdb

  todolistdb:
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: todolistdb

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_NGINX_URL=${VITE_NGINX_URL}
        - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT}
    ports:
      - "3000:3000"
    environment:
      - VITE_NGINX_URL=${VITE_NGINX_URL}
      - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - server
      - socket-server
    restart: always
