version: '3.3'

services:
  server-1:
    build: server
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      PORT: 8080
      HOST: server-1
      FRONTEND_URL: ${FRONTEND_URL}
    links:
      - todolistdb
    depends_on:
      - todolistdb
    networks:
      - loadbalancing

  server-2:
    build: server
    ports:
      - "8081:8080"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      PORT: 8080
      HOST: server-2
      FRONTEND_URL: ${FRONTEND_URL}
    links:
      - todolistdb
    depends_on:
      - todolistdb
    networks:
      - loadbalancing

  socket-server-1:
    build: socket-server
    ports:
      - "9090:9090"
    restart: always
    environment:
      PORT: ${SOCKET_IO_PORT}
      HOST: ${SOCKET_IO_HOST}
      FRONTEND_URL: ${FRONTEND_URL}
    links:
      - todolistdb
      - redis
    depends_on:
      - todolistdb
    networks:
      - loadbalancing

  socket-server-2:
    build: socket-server
    ports:
      - "9091:9090"
    restart: always
    environment:
      PORT: 9090
      HOST: socket-server-2
      FRONTEND_URL: ${FRONTEND_URL}
    links:
      - todolistdb
      - redis
    depends_on:
      - todolistdb
    networks:
      - loadbalancing

  todolistdb:
    build: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - loadbalancing

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: todolistdb
    networks:
      - loadbalancing

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_NGINX_URL=${VITE_NGINX_URL}
        - VITE_FRONTEND_PORT=${VITE_FRONTEND_PORT}
    ports:
      - "3000:3000"
    environment:
      - VITE_NGINX_URL=${VITE_NGINX_URL}
    networks:
      - loadbalancing

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - loadbalancing
    depends_on:
      - frontend
      - server-1
      - server-2
      - socket-server-1
      - socket-server-2
    restart: always

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - loadbalancing

networks:
  loadbalancing:
